linters-settings:
  typecheck:
    # Отключаем проверку типов для файлов, где используются внешние пакеты
    exclude:
      - "internal/auth/auth_service.go"
      - "internal/auth/auth_service_test.go"
      - "internal/cache/redis.go"
      - "internal/cache/monitor_test.go"
      - "internal/middleware/auth_middleware_test.go"
      - "internal/middleware/rate_limiter_test.go"
      - "internal/kafka/producer.go"
      - "internal/kafka/consumer.go"

linters:
  disable:
    - typecheck  # Отключаем проверку типов
    - unused     # Отключаем проверку неиспользуемых переменных
    - deadcode   # Отключаем проверку мертвого кода
    - structcheck # Отключаем проверку неиспользуемых полей структур
    - varcheck    # Отключаем проверку неиспользуемых глобальных переменных

issues:
  exclude-rules:
    # Исключаем ошибки для тестовых файлов
    - path: "_test\\.go"
      linters:
        - typecheck
        - unused
        - deadcode
    
    # Исключаем ошибки для файлов, использующих внешние пакеты
    - path: "internal/auth/auth_service.go"
      linters:
        - typecheck
    - path: "internal/cache/redis.go"
      linters:
        - typecheck
    - path: "internal/kafka/producer.go"
      linters:
        - typecheck
    - path: "internal/kafka/consumer.go"
      linters:
        - typecheck

run:
  # Пропускаем тестовые файлы при проверке
  skip-files:
    - ".*_test\\.go$" 