run:
  timeout: 5m  # Максимальное время выполнения линтера
  tests: true  # Проверять тестовые файлы

linters:
  disable-all: true  # Отключаем все линтеры по умолчанию
  enable:
    - gosimple      # Упрощение кода
    - govet         # Проверка подозрительных конструкций
    - ineffassign   # Обнаружение неэффективных присваиваний
    - staticcheck   # Статический анализ кода
    - typecheck     # Проверка типов как в компиляторе Go
    - gofmt         # Проверка форматирования кода
    - goimports     # Проверка импортов
    - misspell      # Проверка орфографии

issues:
  exclude-dirs:
    - vendor  # Исключаем директорию vendor из проверки
  exclude-rules:
    - path: _test\.go  # Для тестовых файлов
      linters:
        - errcheck  # Отключаем проверку необработанных ошибок в тестах
        - gosec     # Отключаем проверку безопасности в тестах
        - typecheck # Отключаем проверку типов в тестах
    - path: internal/auth/  # Для файлов в директории auth
      linters:
        - typecheck # Отключаем проверку типов
    - path: internal/cache/  # Для файлов в директории cache
      linters:
        - typecheck # Отключаем проверку типов
    - path: internal/kafka/  # Для файлов в директории kafka
      linters:
        - typecheck # Отключаем проверку типов
  max-issues-per-linter: 0  # Без ограничения на количество проблем от одного линтера
  max-same-issues: 0  # Без ограничения на количество одинаковых проблем 