run:
  timeout: 5m
  skip-dirs:
    - logs

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.8

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
    - path: internal/auth/auth_service.go
      linters:
        - typecheck
    - path: internal/cache/redis.go
      linters:
        - typecheck
    - path: internal/kafka/
      linters:
        - typecheck
    - path: internal/middleware/
      linters:
        - typecheck 