version: "3.8"

services:
  app:
    build: .
    container_name: delivery_app
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/database.db
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: delivery_db
    volumes:
      - ./data:/data
